language: node_js
node_js:
  - "6.1"
  - "6.0"
  - 5".11"
  - 5".10"
  - "5.9"
  - "5.8"
  - "5.7"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  - "5.2"
  - "5.1"
  - "5.0"

sudo: false

script:
  - "npm run test-coverage"

after_script:
  - "npm install coveralls@2 && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"

addons:
  code_climate:
    repo_token: cbfd1ce2c7fdfb4d734f661d89fb7d492a976f6586cea6b1c5851ebc71dc8869

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1e2572b1e7e38d54662b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
